## Introduction

In this assessment lab, you will explore basic techniques for retrieving and transforming data using SQL (Structured Query Language) in Python. You will be working with the employees table stored in the data.sqlite file. Imagine that you are working within the HR department of the fictional Northwinds Company as a data specialist/analyst and need to be able to easily access select employee records. SQL is just the tool you need!

SQL is a powerful language that allows us to interact with relational databases and perform various operations on the data. By leveraging SQL queries, we can efficiently retrieve specific subsets of data, create meaningful aliases for improved readability, transform selected columns using CASE statements, and utilize built-in SQL functions to perform advanced transformations.

## Learning Objectives

* Connect to a SQL Database file
* Use SELECT in SQL to select columns from a database
* Use SQL built-in functions to manipulate the values of the given database

## Part 1: Connecting to Data

A SQL database file has been provided that contains the Northwind company's product, customer and employee data (fictional). For the scope of this assessment you will focus mostly on the employees tables. You will be asked to retrieve specific information/data using SQL queries in tandem with Pandas to load the results into a DataFrame.

Example:

`df_answer = pd.read_sql("""SELECT * FROM some_table""", connection)`

### Step 1

In the cell below import the necessary libraries, sqlite3 and pandas. Use the standard alias for the pandas library. Create a connection to the **data.sqlite** database file and store it as the variable conn.

In [1]:
# CodeGrade step1
# Replace None with your code

# SQL Library and Pandas
import sqlite3
import pandas as pd

# Connect to the database
conn = sqlite3.connect('data.sqlite')

As previously stated, this database contains multiple tables but for this assessment you will focus on querying data from the **employees** table and later from the **orderDetails** table. In the cell below we have provided code that selects all columns and rows from the **employees** table for you to use as reference.

In [11]:
# Run this cell without changes
# First look at full table
pd.read_sql("""SELECT * FROM employees""", conn)

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1,,President
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1,1002,VP Sales
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1,1002,VP Marketing
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6,1056,Sales Manager (APAC)
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4,1056,Sale Manager (EMEA)
5,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1,1056,Sales Manager (NA)
6,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1,1143,Sales Rep
7,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1,1143,Sales Rep
8,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2,1143,Sales Rep
9,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2,1143,Sales Rep
10,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3,1143,Sales Rep
11,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3,1143,Sales Rep
12,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4,1102,Sales Rep
13,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4,1102,Sales Rep
14,1401,Castillo,Pamela,x2759,pcastillo@classicmodelcars.com,4,1102,Sales Rep
15,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102,Sales Rep
16,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7,1102,Sales Rep
17,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6,1088,Sales Rep
18,1612,Marsh,Peter,x102,pmarsh@classicmodelcars.com,6,1088,Sales Rep
19,1619,King,Tom,x103,tking@classicmodelcars.com,6,1088,Sales Rep
20,1621,Nishi,Mami,x101,mnishi@classicmodelcars.com,5,1056,Sales Rep
21,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5,1621,Sales Rep
22,1702,Gerard,Martin,x2312,mgerard@classicmodelcars.com,4,1102,Sales Rep

In [3]:
import os
os.listdir()

['.config', 'data.sqlite', 'sample_data']

In [4]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

Empty DataFrame
Columns: [name]
Index: []

In [5]:
import os

os.path.getsize("data.sqlite")

0

In [6]:
import os
os.remove("data.sqlite")

In [8]:
from google.colab import files
uploaded = files.upload()

Saving SQLSelectLab.ipynb to SQLSelectLab.ipynb

In [9]:
conn = sqlite3.connect("data.sqlite")

In [10]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

           name
0  orderdetails
1      payments
2       offices
3     customers
4        orders
5  productlines
6      products
7     employees

## Part 2: Basic Select Filtering

### Step 2
Return the employee number and last name from all employees in the employees table in the database. Your result should only contain those two columns.

In [12]:
# CodeGrade step2
# Replace None with your code

df_name_number = pd.read_sql("""
SELECT employeeNumber, lastName
FROM employees;
""", conn)

df_name_number

   employeeNumber   lastName
0            1002     Murphy
1            1056  Patterson
2            1076   Firrelli
3            1088  Patterson
4            1102     Bondur
5            1143        Bow
6            1165   Jennings
7            1166   Thompson
8            1188   Firrelli
9            1216  Patterson
10           1286      Tseng
11           1323     Vanauf
12           1337     Bondur
13           1370  Hernandez
14           1401   Castillo
15           1501       Bott
16           1504      Jones
17           1611     Fixter
18           1612      Marsh
19           1619       King
20           1621      Nishi
21           1625       Kato
22           1702     Gerard

### Step 3
Repeat Step 2, but have the last name come before the employee number.

In [13]:
# CodeGrade step3
# Replace None with your code

df_reverse = pd.read_sql("""
SELECT lastName, employeeNumber
FROM employees;
""", conn)

df_reverse

     lastName employeeNumber
0      Murphy           1002
1   Patterson           1056
2    Firrelli           1076
3   Patterson           1088
4      Bondur           1102
5         Bow           1143
6    Jennings           1165
7    Thompson           1166
8    Firrelli           1188
9   Patterson           1216
10      Tseng           1286
11     Vanauf           1323
12     Bondur           1337
13  Hernandez           1370
14   Castillo           1401
15       Bott           1501
16      Jones           1504
17     Fixter           1611
18      Marsh           1612
19       King           1619
20      Nishi           1621
21       Kato           1625
22     Gerard           1702

## Part 3: Aliasing in Select

### Step 4
Repeat step 3, but this time use an alias to rename the employee number column as 'ID'.

In [14]:
# CodeGrade step4
# Replace None with your code

df_alias = pd.read_sql("""
SELECT lastName, employeeNumber AS ID
FROM employees;
""", conn)

df_alias

     lastName    ID
0      Murphy  1002
1   Patterson  1056
2    Firrelli  1076
3   Patterson  1088
4      Bondur  1102
5         Bow  1143
6    Jennings  1165
7    Thompson  1166
8    Firrelli  1188
9   Patterson  1216
10      Tseng  1286
11     Vanauf  1323
12     Bondur  1337
13  Hernandez  1370
14   Castillo  1401
15       Bott  1501
16      Jones  1504
17     Fixter  1611
18      Marsh  1612
19       King  1619
20      Nishi  1621
21       Kato  1625
22     Gerard  1702

## Part 4: CASE Function

### Step 5
Use 'CASE' to bin where the jobTitles of President, VP Sales, or VP Marketing have the 'role' of "Executive", and the rest of the employes are "Not Executive".

Define the result of the 'CASE' as a new column called 'role'

Hint: For the WHEN clause if we were looking at Managers, we'd have


```
WHEN jobTitle = "Sales Manager (APAC)" OR jobTitle = "Sale Manager (EMEA)" OR jobTitle = "Sales Manager (NA)" THEN "Manager"
```

In [15]:
# CodeGrade step5
# Replace None with your code

df_executive = pd.read_sql("""
SELECT *,
CASE
    WHEN jobTitle = 'President'
         OR jobTitle = 'VP Sales'
         OR jobTitle = 'VP Marketing'
    THEN 'Executive'
    ELSE 'Not Executive'
END AS role
FROM employees;
""", conn)

df_executive

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle,role
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1,,President,Executive
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1,1002,VP Sales,Executive
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1,1002,VP Marketing,Executive
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6,1056,Sales Manager (APAC),Not Executive
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4,1056,Sale Manager (EMEA),Not Executive
5,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1,1056,Sales Manager (NA),Not Executive
6,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1,1143,Sales Rep,Not Executive
7,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1,1143,Sales Rep,Not Executive
8,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2,1143,Sales Rep,Not Executive
9,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2,1143,Sales Rep,Not Executive
10,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3,1143,Sales Rep,Not Executive
11,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3,1143,Sales Rep,Not Executive
12,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4,1102,Sales Rep,Not Executive
13,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4,1102,Sales Rep,Not Executive
14,1401,Castillo,Pamela,x2759,pcastillo@classicmodelcars.com,4,1102,Sales Rep,Not Executive
15,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102,Sales Rep,Not Executive
16,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7,1102,Sales Rep,Not Executive
17,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6,1088,Sales Rep,Not Executive
18,1612,Marsh,Peter,x102,pmarsh@classicmodelcars.com,6,1088,Sales Rep,Not Executive
19,1619,King,Tom,x103,tking@classicmodelcars.com,6,1088,Sales Rep,Not Executive
20,1621,Nishi,Mami,x101,mnishi@classicmodelcars.com,5,1056,Sales Rep,Not Executive
21,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5,1621,Sales Rep,Not Executive
22,1702,Gerard,Martin,x2312,mgerard@classicmodelcars.com,4,1102,Sales Rep,Not Executive

## Part 5: Built-in Functions - Strings

### Step 6

Find the length of the last name for all employees, return only this data as a new column called 'name_length'.

In [16]:
# CodeGrade step6
# Replace None with your code

df_name_length = pd.read_sql("""
SELECT LENGTH(lastName) AS name_length
FROM employees;
""", conn)

df_name_length

    name_length
0             6
1             9
2             8
3             9
4             6
5             3
6             8
7             8
8             8
9             9
10            5
11            6
12            6
13            9
14            8
15            4
16            5
17            6
18            5
19            4
20            5
21            4
22            6

### Step 7
Return only one new column called 'short_title', that contains the first two letters of each persons job title.

In [17]:
# CodeGrade step7
# Replace None with your code

df_short_title = pd.read_sql("""
SELECT SUBSTR(jobTitle, 1, 2) AS short_title
FROM employees;
""", conn)

df_short_title

   short_title
0           Pr
1           VP
2           VP
3           Sa
4           Sa
5           Sa
6           Sa
7           Sa
8           Sa
9           Sa
10          Sa
11          Sa
12          Sa
13          Sa
14          Sa
15          Sa
16          Sa
17          Sa
18          Sa
19          Sa
20          Sa
21          Sa
22          Sa

## Part 6: Built-in Functions - Numerics

### Bring in another table from the database

In the cell below we have provided a look at a new table within the database provided. This table contains data pertaining to orders placed with the company and has some good numerical and date columns to explore.

In [18]:
# Run this cell without changes

pd.read_sql("""SELECT * FROM orderDetails;""", conn)

     orderNumber productCode quantityOrdered priceEach orderLineNumber
0          10100    S18_1749              30    136.00               3
1          10100    S18_2248              50     55.09               2
2          10100    S18_4409              22     75.46               4
3          10100    S24_3969              49     35.29               1
4          10101    S18_2325              25    108.06               4
...          ...         ...             ...       ...             ...
2991       10425    S24_2300              49    127.79               9
2992       10425    S24_2840              31     31.82               5
2993       10425    S32_1268              41     83.79              11
2994       10425    S32_2509              11     50.32               6
2995       10425    S50_1392              18     94.92               2

[2996 rows x 5 columns]

### Step 8

Find the total amount for all orders, calculated as the sum of rounded total prices, where the total price for each order is the 'priceEach' multiplied by the 'quantityOrdered'. Make sure you are rounding this internal product result.

Hint: Append .sum() to the end of your returned query that contains total price for each order, in order to create the total amount. You could also use the SUM() built-in SQL function as well.

For example:

```
sum_total = pd.read_sql("""
SELECT total_price
FROM some_table
""", conn).sum()
```

In [19]:
# CodeGrade step8
# Replace None with your code

sum_total_price = pd.read_sql("""
SELECT ROUND(priceEach * quantityOrdered) AS total_price
FROM orderdetails;
""", conn).sum()

sum_total_price

total_price    9604251.0
dtype: float64

### Step 9

It is common in other parts of the world as well as the US Military to have dates as Day/Month/Year. Return the original order date column followed by three new columns that display the order date in this format with column names 'day', 'month', and 'year' respectively.

In [20]:
# CodeGrade step9
# Replace None with your code

df_day_month_year = pd.read_sql("""
SELECT orderDate,
       strftime('%d', orderDate) AS day,
       strftime('%m', orderDate) AS month,
       strftime('%Y', orderDate) AS year
FROM orders;
""", conn)

df_day_month_year

      orderDate day month  year
0    2003-01-06  06    01  2003
1    2003-01-09  09    01  2003
2    2003-01-10  10    01  2003
3    2003-01-29  29    01  2003
4    2003-01-31  31    01  2003
..          ...  ..   ...   ...
321  2005-05-29  29    05  2005
322  2005-05-30  30    05  2005
323  2005-05-30  30    05  2005
324  2005-05-31  31    05  2005
325  2005-05-31  31    05  2005

[326 rows x 4 columns]

### Close the connection

In [21]:
# Run this cell without changes

conn.close()